Added step by step quickstart to create project and access API keys i…
rotationalio/ensign pull request #764
Opened 2023-10-04 14:30 UTC by Mikerniker

@pdeziel Hello, I tried adding the steps from the video tutorial. Will wait for feedback and if I need to make other changes. 
Thank you.

### Scope of changes

Added a step by step guide on creating a project and accessing API keys on the platform based on the video tutorials.

### Type of change

- [ ] new feature
- [ ] bug fix
- [X ] documentation
- [ ] testing
- [ ] technical debt
- [ ] other (describe)

### Acceptance criteria

- [ ] Check if the documentation aligns with internal processes 
- [ ] Check for typos or other errors to links 
- [ ] Check for accuracy of information provided

### Definition of Done

- [ ] I have manually tested the change running it locally (having rebuilt all containers) or via unit tests 
- [ ] I have added unit and/or integration tests that cover my changes
- [ ] I have added new test fixtures as needed to support added tests
- [ ] I have updated the dependencies list if necessary (including updating yarn.lock and/or go.sum)
- [ ] I have recompiled and included new protocol buffers to reflect changes I made if necessary
- [ X] Check this box if a reviewer can merge this pull request after approval (leave it unchecked if you want to do it yourself)
- [ ] I have notified the reviewer via Shortcut or Slack that this is ready for review
- [ ] Front-end: Checked sm, md, lg screen resolutions for effective responsiveness
- [ ] Backend-end: Documented service configuration changes or created related devops stories

### Reviewer(s) checklist

- [ ] Front-end: I've reviewed the Figma design and confirmed that changes match the spec.
- [ ] Any new user-facing content that has been added for this PR has been QA'ed to ensure correct grammar, spelling, and understandability.
- [ ] Are there any TODOs in this PR that should be turned into stories?

2023-10-04 16:30 UTC, pdeziel requested changes
Awesome PR, I really like the tips and important sections, they look really good in the docs.

I did have several suggestions to streamline the wording and such but overall this is a great addition.

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +**Steps to Create Your Project and Access Your API Key**
```suggestion
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- After opening an account, click the `Create` button under `Set Up a New Project`.
```suggestion
- After creating an account, click the `Create` button under `Set Up a New Project`.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- Enter a `Project Name` (required) and provide an optional description, then click `Create Project` (You will be redirected to the Projects dashboard).
```suggestion
- Enter a `Project Name` (required) and provide an optional description, then click `Create Project`. You will be redirected to the Projects dashboard.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- Go to the `Design Your Data Flows: Set up Your Topics` section to create topics.
```suggestion
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- Watch the video tutorial at [Ensign Topics](https://www.youtube.com/watch?v=1XuVPl_Ki4U)
```suggestion
- For more details, watch the [Topic Creation Tutorial](https://www.youtube.com/watch?v=1XuVPl_Ki4U)
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - Pick a name for each topic that encodes information about the data that's stored in that topic.
```suggestion
> - Pick a name for each topic that encodes information about the data you intend to store in that topic.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - You can also include information about the data format (e.g. flights-json or hotels-html). Read more at [Naming Topics]({{< ref "/getting-started/topics" >}})
```suggestion
> - You can also include information about the data format (e.g. flights-json or hotels-html). Read more [here]({{< ref "/getting-started/topics" >}})
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- Go to the `Permission Your Data Flows: Generate API Keys` section and click `New Key`.
```suggestion
- Click the `New Key` button.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- A `Generate API Key for project` pop-up will open, add a `Key Name,` and choose `Permissions` (Full Access or Custom Access), then click `Generate API Key`.
```suggestion
- Create a name for the key and select its permissions (Full Access or Custom Access), then click `Generate API Key`.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- From the `Your API Key` popup, copy both the `Client ID` and the `Client Secret` to open a client connection to Ensign. Read More at [Ensign API Keys](#ensign-api-keys)
```suggestion
- Copy or download the `Client ID` and the `Client Secret`, you will need both to connect to Ensign. Read more [here](#ensign-api-keys) 
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +- Watch the video tutorial at [Creating Ensign API Keys](https://www.youtube.com/watch?v=KMejrUIouMw)
```suggestion
- For more details, watch the [API Key Creation Tutorial](https://www.youtube.com/watch?v=KMejrUIouMw)
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - Remember to download your keys and save this file.
```suggestion
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - Do not share your keys with anyone, and never commit them to a public GitHub repository.
```suggestion
> - Do not share your keys with anyone, and never commit them to a public GitHub repository. Read more about best practices for API keys [here](#authentication).
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - Add the `Client ID` and `Client Secret` to your environment variables, or you can put the file into your Git repository via gitignore. Read More at [Authentication](#authentication)
```suggestion
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - API keys are defined at the project level, and everyone collaborating on the datasets will need their own API keys.
```suggestion
> - API keys grant access to all topics in the project.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - Once you add teammates to your project, they can create their own API keys using the same technique.
```suggestion
> - Team members with the `Member`, `Owner`, or `Admin` role can create API keys, an `Observer` can not create API keys.
```

2023-10-04 16:30 UTC, pdeziel commented on docs/content/getting-started/_index.md
> +> - New API keys enable users or applications to publish new data to the project topics, or to subscribe to those topics.
```suggestion
```

2023-10-04 17:06 UTC, Mikerniker commented
Okay, thank you @pdeziel , I tried to commit your suggestions, I'm not sure if I did this correctly, but let me know if I missed something or if I still need to make other changes. Thank you for your help
.

2023-10-04 17:30 UTC, pdeziel approved these changes
Looks great, thanks for making the updates! I'll merge the PR once the checks pass.

2023-10-04 17:32 UTC, Mikerniker commented
Ok, thanks @pdeziel !

2023-10-04 18:06 UTC, Mikerniker commented
Okay, let me try to study  and figure out how to set up a GPG key and if I get lost, I'll maybe go for the second option. Will get back on this when or if I am able to set it up. Thanks!

2023-10-05 15:29 UTC, Mikerniker commented
Hi @pdeziel I have set up the GPG signature and I'm currently trying to figure out how to open a new PR. --> when I click open a new PR I keep getting redirected to this page... am I supposed to click "Close with comment" button here first? Sorry, I'm still new at making PRs...

2023-10-05 15:48 UTC, pdeziel commented
> Hi @pdeziel I have set up the GPG signature and I'm currently trying to figure out how to open a new PR. --> when I click open a new PR I keep getting redirected to this page... am I supposed to click "Close with comment" button here first? Sorry, I'm still new at making PRs...

@Mikerniker The way I would do it is create a new branch on your fork and open a PR from that one with the signed commit. Unfortunately if you add signed commits on this branch it still won't work, because the original commit you added here yesterday was not signed and it wants all the commits to be signed.

2023-10-05 15:51 UTC, Mikerniker commented
Ok got it, will try that now, thanks!

2023-10-05 17:26 UTC, closed without merging